### PR TITLE
[18.0][FIX] storage_media: missing deletion of files

### PR DESCRIPTION
**Pull request by henrybackman**
The `unlink` hook was missing from the storage media, causing the files not being marked to be deleted when a storage media record was deleted

### CODE REVIEW

**Comment by henrybackman** [comment]
There is an unrelated error failing the tests:
```
2026-05-12 08:56:53,019 313 CRITICAL odoo odoo.modules.module: Couldn't load module base 
2026-05-12 08:56:53,024 313 ERROR odoo odoo.modules.registry: Failed to load registry 
2026-05-12 08:56:53,024 313 CRITICAL odoo odoo.service.server: Failed to initialize database `odoo`. 
Traceback (most recent call last):
  File "/opt/odoo/odoo/service/server.py", line 1366, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/opt/odoo/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 431, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "/opt/odoo/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/opt/odoo/odoo/addons/base/__init__.py", line 5, in <module>
    from . import models
  File "/opt/odoo/odoo/addons/base/models/__init__.py", line 22, in <module>
    from . import ir_mail_server
  File "/opt/odoo/odoo/addons/base/models/ir_mail_server.py", line 15, in <module>
    import OpenSSL
  File "/opt/odoo-venv/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/odoo-venv/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1579, in <module>
    class X509StoreFlags(object):
  File "/opt/odoo-venv/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1598, in X509StoreFlags
    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
```

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
the build on 18.0 branch is broken already https://github.com/OCA/storage/issues/602

**Review by vvrossem — APPROVED** [review]
